# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OhQ15Dj3WwISrv6u_CecbmTe127uwwUd
"""

print("asdsdasdasd")